/* eslint-disable @typescript-eslint/no-require-imports -- Standalone CommonJS Playwright entrypoint, outside the Next.js app. */
// Assessment fixture UI contract checks. No shared backend or qc global setup.
const { test, expect } = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
const fixtureDir = path.resolve(__dirname, '../../../internal/api/testdata/assessment-responses');
const messages = require('../../messages/en.json');
const fixture = (name) => JSON.parse(fs.readFileSync(path.join(fixtureDir, `${name}.json`), 'utf8'));
const list = (items) => ({ items, total: items.length, page: 1, page_size: 20, limit: 20 });

// Only the shell/list wrappers are synthetic here. Every assessment detail is an
// untouched checked-in HTTP response generated by a handler test with synthetic input.
function shellResponses() {
  const featureRegistry = ['phishing-detection', 'spoofing-detection', 'agent-center'].map((id) => ({
    id, visibility: 'ALWAYS', scope: 'tenant', platformAccess: 'edit', tenantAccess: 'edit',
    platformHidden: false, grantable: false,
  }));
  return new Map(Object.entries({
    '/bootstrap': { form: 'ai-multi', capabilities: { ai: true, multiTenant: true, saas: false },
      branding: { deployment: 'self-hosted' }, user: { role: 'system_admin', tenantId: null },
      featureRegistry, grants: [], localAuthEnabled: false },
    '/roles/1': { id: 1, code: 'super_admin', status: 'normal', isSuperAdmin: true, permissions: [] },
    '/profile/account': { username: 'assessment-fixture', name: 'Assessment fixture', role: 'system_admin', tenant_id: null, email: '', phone: '', created_at: '', last_login_at: '' },
    '/mail-logs/fields': { fields: [] },
    '/spoofing-agent/engine-config': { enabled: true, run_mode: 'realtime', default_mark_style: { positions: [] }, caps: { max_persons: 100, max_brands: 100, max_legit_emails_per_person: 10, max_domains_per_brand: 10, max_whitelist_entries: 100 } },
    '/version': { version: 'assessment-fixture', commit: 'synthetic', build_time: '' },
    '/tenants': list([]),
    '/agent-center/overview': { agents: ['phishing', 'spoofing'].map((key) => ({
      key, feature_id: `${key}-detection`, access: 'enabled', status: 'running', stage_position: 'sideline',
      today_processed: 1, hit_count: 1, processed_count: 1, hit_rate: 1, fallback_count: 0,
    })) },
    '/phishing-agent/control': { enabled: true, revision: 1 },
    '/phishing-agent/admission-rules': list([]),
    '/phishing-agent/stats': { today_detected: 1, today_quarantined: 0, pending_review: 1, today_recalled: 0, recall_success: 0 },
    '/spoofing-agent/stats': { today_detected: 1, today_intercepted: 0, pending_review: 1, displayname_hits: 1, brand_hits: 1 },
    '/unified-rules': list([]),
  }));
}

async function isolate(page, context, testInfo, responses, errorPaths = new Set()) {
  const baseURL = testInfo.project.use.baseURL || process.env.ASSESSMENT_FIXTURE_WEB_URL;
  if (!baseURL) throw new Error('ASSESSMENT_FIXTURE_WEB_URL or Playwright baseURL must target an isolated frontend');
  const origin = new URL(baseURL).origin;
  const audit = { fixtureRequests: [], frontendDiagnostics: [], consoleDiagnostics: [], blockedRequests: [], pageErrors: [], dialogs: [] };
  page.on('console', (message) => {
    if (['warning', 'error'].includes(message.type())) audit.consoleDiagnostics.push({ type: message.type(), text: message.text() });
  });
  page.on('pageerror', (error) => audit.pageErrors.push(error.message));
  page.on('dialog', async (dialog) => { audit.dialogs.push(dialog.message()); await dialog.dismiss(); });
  await context.addCookies([{ name: 'osgateway_token', value: 'synthetic-browser-fixture-only', url: origin, httpOnly: true }]);
  await context.addInitScript(() => {
    localStorage.setItem('osgateway_user', JSON.stringify({ id: 1, username: 'assessment-fixture', role: 'system_admin',
      role_id: 1, tenant_id: null, is_super_admin: true, created_at: '', updated_at: '' }));
    localStorage.removeItem('osgateway_mock_enabled');
    localStorage.removeItem('osgateway_demo_session');
    localStorage.removeItem('osgateway_selected_tenant');
    document.cookie = 'osg_viewer=platform; path=/; SameSite=Strict';
  });
  // Installed before the first navigation. Unknown APIs, writes, and external
  // requests are aborted AND audited; there is no backend fallback.
  await context.route('**/*', async (route) => {
    const request = route.request();
    const url = new URL(request.url());
    if (url.origin === origin && request.method() === 'POST' && url.pathname === '/__nextjs_original-stack-frames') {
      // Next.js devtools resolves console-warning stacks here. Fulfill locally;
      // this is a frontend diagnostic, never a forwarded backend request.
      audit.frontendDiagnostics.push(url.pathname);
      return route.fulfill({ status: 200, contentType: 'application/json', body: '[]' });
    }
    const apiPath = url.pathname.startsWith('/api/v1/') ? url.pathname.slice('/api/v1'.length) : null;
    if (url.origin === origin && apiPath && request.method() === 'GET' && responses.has(apiPath)) {
      audit.fixtureRequests.push(apiPath);
      return route.fulfill({ status: errorPaths.has(apiPath) ? 503 : 200, contentType: 'application/json',
        body: JSON.stringify(errorPaths.has(apiPath) ? { error: { code: 'fixture_unavailable', message: 'Synthetic detail endpoint failure' } } : responses.get(apiPath)) });
    }
    const frontend = url.origin === origin && request.method() === 'GET' && (
      url.pathname.startsWith('/_next/') || /^\/en\/(agent-center\/overview|investigations|logs\/email)$/.test(url.pathname)
      || /\.(?:woff2?|png|svg|ico)$/.test(url.pathname)
    );
    if (frontend && !url.pathname.startsWith('/api/')) return route.continue();
    audit.blockedRequests.push(`${request.method()} ${request.url()}`);
    return route.abort('blockedbyclient');
  });
  await context.routeWebSocket('**/*', (socket) => {
    // The isolated Next.js dev server may use HMR; no backend socket is needed.
    const url = new URL(socket.url());
    if (url.host === new URL(origin).host && url.pathname.startsWith('/_next/')) {
      socket.connectToServer();
      return;
    }
    audit.blockedRequests.push(`WEBSOCKET ${socket.url()}`);
    socket.close();
  });
  return async () => {
    await testInfo.attach('fixture-network-audit', { body: JSON.stringify(audit, null, 2), contentType: 'application/json' });
    expect(audit.blockedRequests, 'all APIs/external calls must be explicitly accounted for').toEqual([]);
    expect(audit.pageErrors, 'real routes must not throw on handler response shapes').toEqual([]);
    expect(audit.dialogs, 'source text must never execute script').toEqual([]);
  };
}

async function openDrawer(page, kind, data) {
  const agent = kind === 'phish' ? 'phishing' : 'spoofing';
  await page.goto(`/en/agent-center/overview?agent=${agent}&tab=overview`);
  await page.getByTestId(kind === 'phish' ? `phishing-log-detail-${data.summary.sideline_id}` : 'spoof-log-row-detail').click();
  return page.getByTestId(kind === 'phish' ? 'phishing-detail-sheet' : 'spoof-detail-sheet');
}

function drawerResponses(kind, data) {
  const responses = shellResponses();
  const prefix = kind === 'phish' ? '/phishing-agent/detection-logs' : '/spoofing-agent/detection-logs';
  const id = kind === 'phish' ? data.summary.sideline_id : data.summary.id;
  responses.set(prefix, list([data.summary]));
  responses.set(`${prefix}/${encodeURIComponent(id)}`, data);
  return responses;
}

async function assertReport(container, result) {
  const reportView = container.getByTestId('assessment-report');
  await expect(reportView).toBeVisible();
  const report = result.assessment_report;
  if (result.assessment_report_status !== 'available') {
    await expect(reportView.getByTestId('assessment-state')).toHaveText(messages.assessment.states[result.assessment_report_status]);
    if (result.assessment_report_reason) await expect(reportView).toContainText(messages.assessment.reasons[result.assessment_report_reason]);
    await expect(reportView.getByTestId('assessment-factor')).toHaveCount(0);
    await expect(reportView.getByTestId('assessment-source')).toHaveCount(0);
    return;
  }
  const factors = report.factors || [];
  await expect(reportView.getByTestId('assessment-factor')).toHaveCount(factors.length);
  if (!factors.length) await expect(reportView.getByTestId('assessment-state')).toHaveText(messages.assessment.empty);
  await expect(reportView.getByTestId('assessment-subject')).toHaveCount(report.subjects.length);
  for (const subject of report.subjects) {
    const group = reportView.getByTestId('assessment-subject').filter({ has: container.page().getByRole('heading', { name: subject.label, exact: true }) });
    await expect(group).toHaveCount(1);
    const subjectFactors = factors.filter((factor) => factor.subject_ref === subject.id);
    await expect(group.getByTestId('assessment-factor')).toHaveCount(subjectFactors.length);
    for (const factor of subjectFactors) {
      const card = group.getByTestId('assessment-factor').filter({ hasText: factor.observation });
      await expect(card).toContainText(factor.relevance);
      await expect(card).toContainText(factor.limitation);
      await expect(group.getByTestId('assessment-direction')).toContainText([messages.assessment.directions[factor.direction]]);
      for (let i = 0; i < factor.source_refs.length; i++) {
        const source = report.sources.find((item) => item.id === factor.source_refs[i]);
        const detail = card.getByTestId('assessment-source').nth(i);
        await expect(detail).not.toHaveAttribute('open', '');
        await expect(detail.getByTestId('assessment-source-content')).not.toBeVisible();
        await detail.locator('summary').click();
        await expect(detail).toHaveAttribute('open', '');
        await expect(detail.getByTestId('assessment-source-content')).toHaveText(source.content);
        await expect(detail).toContainText(`Retained ${source.retained_bytes} of ${source.original_bytes} captured bytes`);
        await expect(detail.locator('script')).toHaveCount(0);
        await detail.locator('summary').click();
        await expect(detail.getByTestId('assessment-source-content')).not.toBeVisible();
      }
    }
  }
  const cited = new Set(factors.flatMap((factor) => factor.source_refs));
  const uncited = report.sources.filter((source) => !cited.has(source.id));
  if (uncited.length) {
    const section = reportView.getByTestId('assessment-uncited-sources');
    await expect(section.getByTestId('assessment-source')).toHaveCount(uncited.length);
    for (let i = 0; i < uncited.length; i++) {
      const source = uncited[i];
      const detail = section.getByTestId('assessment-source').nth(i);
      await expect(detail.getByTestId('assessment-source-content')).not.toBeVisible();
      await detail.locator('summary').click();
      await expect(detail.getByTestId('assessment-source-content')).toHaveText(source.content);
      await expect(detail).toContainText(`Retained ${source.retained_bytes} of ${source.original_bytes} captured bytes`);
      await expect(detail).toContainText(messages.assessment.outcomes[source.outcome]);
      await expect(detail.locator('script')).toHaveCount(0);
      await detail.locator('summary').click();
      await expect(detail.getByTestId('assessment-source-content')).not.toBeVisible();
    }
  }
  for (const gap of report.gaps || []) await expect(reportView.getByTestId('assessment-gaps')).toContainText(gap.detail);
}

async function captureReport(container, testInfo, label, subjectLabel) {
  await container.page().setViewportSize({ width: 1280, height: 960 });
  const report = container.getByTestId('assessment-report');
  const sources = report.getByTestId('assessment-source');
  for (let i = 0; i < await sources.count(); i++) {
    if (await sources.nth(i).getAttribute('open') === null) await sources.nth(i).locator('summary').click();
  }
  const heading = subjectLabel ? report.getByRole('heading', { name: subjectLabel, exact: true }) : report.getByRole('heading').first();
  await heading.evaluate((element) => element.scrollIntoView({ block: 'start', behavior: 'instant' }));
  await expect(heading).toBeVisible();
  await container.page().evaluate(() => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  const screenshot = testInfo.outputPath(`${label}.png`);
  await container.page().screenshot({ path: screenshot, animations: 'disabled' });
  await testInfo.attach(label, { path: screenshot, contentType: 'image/png' });
}

for (const name of ['phish-available', 'phish-empty', 'phish-pending', 'phish-legacy', 'phish-unsupported', 'phish-failed', 'phish-external-audit',
  'spoof-available', 'spoof-available-task', 'spoof-not-applicable', 'spoof-capacity', 'spoof-legacy-inline', 'spoof-compatibility']) {
  test(`actual ${name} response renders in agent drawer`, async ({ page, context }, testInfo) => {
    const data = fixture(name);
    const kind = name.startsWith('phish') ? 'phish' : 'spoof';
    const finish = await isolate(page, context, testInfo, drawerResponses(kind, data));
    try {
      const drawer = await openDrawer(page, kind, data);
      await assertReport(drawer, data.investigation.result);
      if (['phish-available', 'phish-empty', 'phish-failed', 'spoof-available'].includes(name)) await captureReport(drawer, testInfo, name);
    } finally { await finish(); }
  });
}

for (const name of ['phish-available', 'phish-empty', 'phish-pending', 'phish-unsupported', 'phish-failed', 'phish-legacy', 'phish-external-audit',
  'spoof-available', 'spoof-not-applicable', 'spoof-capacity', 'manual-available']) {
  test(`actual ${name} response renders in investigations route`, async ({ page, context }, testInfo) => {
    const data = fixture(`${name}-investigation`);
    const responses = shellResponses();
    responses.set('/investigations', list([data.task]));
    responses.set(`/investigations/${data.task.id}`, data);
    const finish = await isolate(page, context, testInfo, responses);
    try {
      await page.goto(`/en/investigations?task_id=${data.task.id}`);
      await assertReport(page.getByRole('dialog'), data.task.result);
      if (name === 'phish-available') await captureReport(page.getByRole('dialog'), testInfo, 'generic-investigation');
    } finally { await finish(); }
  });
}

for (const name of ['phish-available', 'spoof-available']) {
  test(`actual ${name} response opens through mail detail modal`, async ({ page, context }, testInfo) => {
    const data = fixture(`${name}-investigation`);
    const summary = fixture(name).summary;
    const mailId = summary.mail_log_id || 1001;
    const mail = { id: mailId, message_id: summary.message_id, sender: summary.sender, recipients: summary.recipients,
      subject: summary.subject, created_at: summary.sidelined_at, action: 'sideline', status: 'sidelined',
      client_ip: '192.0.2.1', matched_rules: [], recipient_dispositions: [] };
    const responses = shellResponses();
    responses.set('/mail-logs', list([mail]));
    responses.set(`/mail-logs/${mailId}`, mail);
    responses.set(`/mail-logs/${mailId}/events`, list([]));
    responses.set('/investigations', list([data.task]));
    responses.set(`/investigations/${data.task.id}`, data);
    const finish = await isolate(page, context, testInfo, responses);
    try {
      await page.goto(`/en/logs/email?mail_log_id=${mailId}`);
      const mailModal = page.getByTestId('email-log-detail-modal');
      await expect(mailModal).toBeVisible();
      await mailModal.getByRole('button').filter({ hasText: data.task.id }).click();
      // The shared investigation dialog is a sibling of the original mail modal.
      const investigation = page.getByRole('dialog').filter({ has: page.getByTestId('assessment-report') });
      await assertReport(investigation, data.task.result);
      await captureReport(investigation, testInfo, `${name}-mail-modal`);
    } finally { await finish(); }
  });
}

for (const name of ['phish-available', 'phish-failed']) {
  test(`existing JSON export preserves ${name} report and status reason`, async ({ page, context }, testInfo) => {
    const data = fixture(name);
    const finish = await isolate(page, context, testInfo, drawerResponses('phish', data));
    try {
      const drawer = await openDrawer(page, 'phish', data);
      await expect(drawer.getByTestId('assessment-report')).toBeVisible();
      await drawer.getByTestId('phishing-detail-run-log').click();
      const downloaded = page.waitForEvent('download');
      await drawer.getByTestId('phishing-detail-export').click();
      const download = await downloaded;
      expect(download.suggestedFilename()).toContain(data.summary.sideline_id);
      const saved = testInfo.outputPath(`${name}.json`);
      await download.saveAs(saved);
      expect(JSON.parse(fs.readFileSync(saved, 'utf8'))).toEqual(data);
      await testInfo.attach('existing-phish-json-export', { path: saved, contentType: 'application/json' });
    } finally { await finish(); }
  });
}

// Explicit UI-only variation: this is not an additional captured API response.
// The base fixture remains unchanged on disk. Cover a legitimate factor under
// one protected subject alongside the base report's threat/uncertainty factors.
test('synthetic UI variation groups strong legitimate support by protected subject', async ({ page, context }, testInfo) => {
  const data = fixture('spoof-available');
  const factor = data.investigation.result.assessment_report.factors[1];
  factor.direction = 'supports_legitimate';
  factor.strength = 'strong';
  const finish = await isolate(page, context, testInfo, drawerResponses('spoof', data));
  try {
    const drawer = await openDrawer(page, 'spoof', data);
    await assertReport(drawer, data.investigation.result);
    const finance = drawer.getByTestId('assessment-subject').filter({ has: page.getByRole('heading', { name: 'Example Finance', exact: true }) });
    await expect(finance).toContainText('Supports legitimate');
    await expect(finance).toContainText('Strength: Strong');
    await captureReport(drawer, testInfo, 'synthetic-strong-legitimate-multi-subject', 'Example Finance');
  } finally { await finish(); }
});

for (const surface of ['phish', 'spoof', 'investigation']) {
  test(`synthetic transport failure shows assessment error in ${surface}`, async ({ page, context }, testInfo) => {
    const generic = surface === 'investigation';
    const data = fixture(generic ? 'phish-available-investigation' : `${surface}-available`);
    const responses = generic ? shellResponses() : drawerResponses(surface, data);
    let detailPath;
    if (generic) {
      detailPath = `/investigations/${data.task.id}`;
      responses.set('/investigations', list([data.task]));
      responses.set(detailPath, data);
    } else {
      detailPath = surface === 'phish' ? `/phishing-agent/detection-logs/${data.summary.sideline_id}`
        : `/spoofing-agent/detection-logs/${encodeURIComponent(data.summary.id)}`;
    }
    const finish = await isolate(page, context, testInfo, responses, new Set([detailPath]));
    try {
      let container;
      if (generic) {
        await page.goto(`/en/investigations?task_id=${data.task.id}`);
        container = page.getByRole('dialog');
      } else container = await openDrawer(page, surface, data);
      await expect(container.getByTestId('assessment-state')).toHaveText(messages.assessment.states.error, { timeout: 15000 });
      await expect(container.getByTestId('assessment-factor')).toHaveCount(0);
      await captureReport(container, testInfo, `${surface}-transport-error`);
    } finally { await finish(); }
  });
}
